[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version="0.8.23"
libraries = ["src/libraries/TradingCommonUtils.sol:TradingCommonUtils:0x34541d846ff366e35431a66050C11CfB1405f9a5", 
             "src/libraries/ArrayGetters.sol:ArrayGetters:0xeAcd6367A347862210eE4C6B6924697Ee9c78c06", 
             "src/libraries/TradingStorageUtils.sol:TradingStorageUtils:0x5AA3B76Cd681A7fc891b4B320466970B9D1856F6",
             "src/libraries/PackingUtils.sol:PackingUtils:0x7835cbb49D36C1E88CBB4a76e57323a8aebb31f8",
             "src/libraries/updateLeverage/UpdateLeverageLifecycles.sol:UpdateLeverageLifecycles:0x86b5E5C11755E9489e0149b760D98Bb26fd8fAa9",
             "src/libraries/updatePositionSize/UpdatePositionSizeLifecycles.sol:UpdatePositionSizeLifecycles:0x510Ea73994625A0c1094E0be8409a6AFC322A3eE"
               ]
